# for flm pretrain (only fm loss)

name: flm
backbone: dit  # dit / dimamba / hf_dit
parameterization: mean
time_conditioning: True
T: 0  
subs_masking: False
causal_attention: False
gumbel_tau_log10_start: -1.0
gumbel_tau_log10_end: -1.0
curriculum_start: 0
curriculum_end: 1000000
flow_loss_type: ce 
ignore_bos: False
t_max: 1.0
t_min: 0.0
pred_log_interval: 2000
double_temb: False
use_discrete_schedule: True
time_condition: alpha_t
loss_scale: none
learnable_loss_weighting: False
