name: duo
backbone: dit  # dit / dimamba / hf_dit
parameterization: mean
time_conditioning: True
T: 0  # 0 (continuous time) / 1000 
subs_masking: False
causal_attention: False
gumbel_tau_log10_start: -1.0
gumbel_tau_log10_end: -5.0
curriculum_start: 0
curriculum_end: 100_000
integral_cache_path: ${hydra:runtime.cwd}/integral/${data.tokenizer_name_or_path}.pkl
ignore_bos: False
gamma_min: -3.5
gamma_max: -1.75
t_min: 0.35
t_max: 0.15
training.loss_type: flow
training.pred_type: x0
sampling.noise_removal: flow
use_curriculum: True
