# for flm pretrain (only fm loss)

name: flm_distill_double
backbone: dit  # dit / dimamba / hf_dit
parameterization: mean
time_conditioning: True
T: 0  # 0 (continuous time) / 1000 
teacher_f_path: null
teacher_g_path: null
subs_masking: False
causal_attention: False
ignore_bos: False
use_curriculum: True
double_temb: True
add_boundary: True
bootstrap_ema: True
learnable_loss_weighting: False